title: "CarNews"
description: "Notícias, informações e curiosidades do mundo automotivo."
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /:categories/:year/:month/:day/:title/

header_pages:
  - noticias.md
  - modelos.md
  - curiosidades.md
  - about.md

  